source-tables:
  - "experiments-production"
  - "samples-production"
  - "projects-production"

source-buckets:
  - "processed-matrix-production"
  - "biomage-source-production"
  - "cell-sets-production"

user-pool-id: "eu-west-1_sVQL15Yxu"

staging-experiments-table: "experiments-staging"
staging-projects-table: "projects-staging"

production-experiments-table: "experiments-production"