source-tables:
  - "experiments-staging"
  - "samples-staging"

source-buckets:
  - "processed-matrix-staging"
  - "biomage-source-staging"

staging-experiments-table: "experiments-staging"
production-experiments-table: "experiments-staging"
