source-tables:
  - "projects-production"
  - "experiments-production"
  - "samples-production"

source-buckets:
  - "processed-matrix-production"
  - "biomage-source-production"
  - "cell-sets-production"

user-pool-id-production: " eu-west-1_ZmmBYI6jO"
user-pool-id-staging: "eu-west-1_sVQL15Yxu"

staging-projects-table: "projects-staging"
staging-experiments-table: "experiments-staging"
staging-samples-table: "samples-staging"

production-experiments-table: "experiments-production"