name: Test biomage-utils
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test biomage-utils
    runs-on: ubuntu-20.04
    steps:
    - id: checkout
      name: Check out source code
      uses: actions/checkout@v2

    - id: test
      name: Run tests
      run: |-
        make install
        make test
